name: Update Changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.release.target_commitish }}
          # Credentials must persist so git-auto-commit-action can push the CHANGELOG update.
          persist-credentials: true

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36 # v1.12.0
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: 'chore: update changelog for ${{ github.event.release.tag_name }}'
          file_pattern: CHANGELOG.md
          commit_user_name: 'Eser Deniz'
          commit_user_email: 'srwiez@gmail.com'
          commit_author: 'Eser Deniz <srwiez@gmail.com>'
